(() => {
const D=window.PA_DATA;
const DB_NAME="notas-direito-pratica"; const DB_VERSION=1;
let db, current=[], index=0, selected=null, sessionMode="daily";
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains("attempts"))d.createObjectStore("attempts",{keyPath:"id"});if(!d.objectStoreNames.contains("mastery"))d.createObjectStore("mastery",{keyPath:"node"});if(!d.objectStoreNames.contains("sessions"))d.createObjectStore("sessions",{keyPath:"id"});};r.onsuccess=()=>{db=r.result;resolve(db)};r.onerror=()=>reject(r.error);})}
function all(store){return new Promise((res,rej)=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function put(store,value){return new Promise((res,rej)=>{const r=db.transaction(store,"readwrite").objectStore(store).put(value);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function node(id){return D.nodes.find(n=>n.id===id)} function content(id){return D.contents.find(c=>c.id===id)}
function fmtDate(d){return new Intl.DateTimeFormat("pt-BR").format(new Date(d))}
function nextDate(level,correct){const days=correct?[1,3,7,15,30,60][Math.min(level,5)]:1;const d=new Date();d.setDate(d.getDate()+days);return d.toISOString()}
async function stats(){const attempts=await all("attempts");const mastery=await all("mastery");const errors=attempts.filter(a=>!a.correct);const acertos=attempts.filter(a=>a.correct).length;$("#kpi-hoje").textContent=D.questions.length;$("#kpi-nos").textContent=D.nodes.length;$("#kpi-erros").textContent=errors.length;$("#kpi-acerto").textContent=attempts.length?Math.round(acertos/attempts.length*100)+"%":"—";$("#d-tentativas").textContent=attempts.length;$("#d-acertos").textContent=acertos;$("#d-percentual").textContent=attempts.length?Math.round(acertos/attempts.length*100)+"%":"—";$("#d-dominados").textContent=mastery.filter(m=>m.level>=3).length;renderErrors(errors);renderMastery(mastery)}
function renderToday(){const byNode={};D.questions.forEach(q=>(byNode[q.primaryNode]??=[]).push(q));$("#lista-hoje").innerHTML=D.nodes.map(n=>`<div class="pa-item"><div><strong>${n.titulo}</strong><br><small>${n.disciplina} · ${n.tema}</small></div><span class="pa-badge">${(byNode[n.id]||[]).length} questões</span></div>`).join("")}
function renderContents(){ $("#lista-conteudos").innerHTML=D.contents.map(c=>`<div class="pa-item"><div><strong>${c.titulo}</strong><br><small>${c.nodes.map(id=>node(id)?.titulo).filter(Boolean).join(" · ")}</small></div><div><a class="pa-secondary" href="${c.url}">Estudar</a> <button class="pa-primary praticar-conteudo" data-content="${c.id}">Praticar</button></div></div>`).join(""); $$(".praticar-conteudo").forEach(b=>b.onclick=()=>start(D.questions.filter(q=>q.contentId===b.dataset.content),"content"))}
function renderErrors(errors){const host=$("#lista-erros");if(!errors.length){host.innerHTML='<div class="pa-empty">Nenhum erro registrado ainda.</div>';return}const latest=[...errors].reverse().slice(0,25);host.innerHTML='<table class="pa-table"><thead><tr><th>Questão</th><th>Assunto</th><th>Data</th></tr></thead><tbody>'+latest.map(a=>{const q=D.questions.find(x=>x.id===a.questionId);return q?`<tr><td>${q.prompt}</td><td>${node(q.primaryNode)?.titulo||""}</td><td>${fmtDate(a.date)}</td></tr>`:""}).join("")+'</tbody></table>'}
function renderMastery(items){const host=$("#tabela-dominio");if(!items.length){host.innerHTML='<div class="pa-empty">O domínio começará a ser calculado depois das primeiras respostas.</div>';return}host.innerHTML='<table class="pa-table"><thead><tr><th>Assunto</th><th>Nível</th><th>Próxima revisão</th></tr></thead><tbody>'+items.map(m=>`<tr><td>${node(m.node)?.titulo||m.node}</td><td>${["Novo","Aprendizagem","Consolidação","Consolidação avançada","Dominado"][Math.min(m.level,4)]}</td><td>${fmtDate(m.nextReview)}</td></tr>`).join("")+'</tbody></table>'}
function populateFilters(){[...new Set(D.nodes.map(n=>n.disciplina))].sort().forEach(v=>$("#f-disciplina").insertAdjacentHTML("beforeend",`<option>${v}</option>`));[...new Set(D.nodes.map(n=>n.tema))].sort().forEach(v=>$("#f-tema").insertAdjacentHTML("beforeend",`<option>${v}</option>`))}
function start(list,mode){if(!list.length){alert("Nenhuma questão disponível para esse recorte.");return}sessionMode=mode;current=[...list].sort(()=>Math.random()-.5);index=0;selected=null;$("#sessao").hidden=false;renderQuestion();$("#sessao").scrollIntoView({behavior:"smooth",block:"start"})}
function renderQuestion(){const q=current[index];if(!q){finish();return}const n=node(q.primaryNode),c=content(q.contentId);$("#sessao").innerHTML=`<div class="pa-question"><div class="pa-progress"><div style="width:${Math.round(index/current.length*100)}%"></div></div><div class="pa-meta"><span class="pa-chip">${n?.disciplina||""}</span><span class="pa-chip">${n?.tema||""}</span><span class="pa-chip">${q.origin}</span><span class="pa-chip">dificuldade ${q.difficulty}</span></div><h2>${q.prompt}</h2><div class="pa-options">${q.options.map((o,i)=>`<button class="pa-option" data-i="${i}">${String.fromCharCode(65+i)}) ${o}</button>`).join("")}</div><div class="pa-actions"><button id="responder" class="pa-primary">Responder</button><button id="pular" class="pa-secondary">Pular</button></div><div id="feedback" class="pa-feedback"></div></div>`; $$(".pa-option").forEach(b=>b.onclick=()=>{selected=Number(b.dataset.i);$$(".pa-option").forEach(x=>x.classList.remove("selecionada"));b.classList.add("selecionada")});$("#responder").onclick=answer;$("#pular").onclick=()=>{index++;selected=null;renderQuestion()}}
async function answer(){const q=current[index];if(selected===null){alert("Selecione uma alternativa.");return}const correct=selected===q.answer;const attempts=await all("attempts");const previous=(await all("mastery")).find(m=>m.node===q.primaryNode);const level=correct?Math.min((previous?.level||0)+1,4):Math.max((previous?.level||1)-1,0);const now=new Date().toISOString();await put("attempts",{id:"A-"+Date.now()+"-"+Math.random().toString(36).slice(2),questionId:q.id,node:q.primaryNode,correct,selected,date:now,mode:sessionMode});await put("mastery",{node:q.primaryNode,level,lastReview:now,nextReview:nextDate(level,correct),attempts:(previous?.attempts||0)+1});const f=$("#feedback");f.className="pa-feedback show "+(correct?"ok":"erro");f.innerHTML=`<strong>${correct?"Correto.":"Resposta incorreta."}</strong><p>${q.explanation}</p><p><a href="${content(q.contentId)?.url||"#"}">Rever conteúdo relacionado →</a></p><div class="pa-actions"><button id="certeza" class="pa-secondary">Tive certeza</button><button id="duvida" class="pa-secondary">Estava em dúvida</button><button id="continuar" class="pa-primary">Próxima questão</button></div>`;$("#continuar").onclick=()=>{index++;selected=null;renderQuestion()};$("#certeza").onclick=()=>confidence("certeza");$("#duvida").onclick=()=>confidence("duvida");await stats()}
async function confidence(value){const arr=await all("attempts");const last=arr.sort((a,b)=>a.date.localeCompare(b.date)).at(-1);if(last){last.confidence=value;await put("attempts",last)}}
function finish(){$("#sessao").innerHTML=`<div class="pa-box"><h2>Sessão concluída</h2><p>Foram percorridas ${current.length} questões. O histórico foi salvo localmente e já influencia o painel de desempenho.</p><button class="pa-primary" id="nova">Voltar ao painel</button></div>`;$("#nova").onclick=()=>{$("#sessao").hidden=true;window.scrollTo({top:0,behavior:"smooth"})};stats()}
function setupTabs(){$$(".pa-tab").forEach(b=>b.onclick=()=>{$$(".pa-tab").forEach(x=>x.classList.remove("ativo"));$$(".pa-painel").forEach(x=>x.classList.remove("ativo"));b.classList.add("ativo");$("#painel-"+b.dataset.tab).classList.add("ativo")})}
async function init(){await openDB();setupTabs();renderToday();renderContents();populateFilters();$("#btn-revisao").onclick=async()=>{const mastery=await all("mastery");const attempts=await all("attempts");const wrongIds=new Set(attempts.filter(a=>!a.correct).map(a=>a.questionId));const dueNodes=new Set(mastery.filter(m=>new Date(m.nextReview)<=new Date()).map(m=>m.node));let list=D.questions.filter(q=>wrongIds.has(q.id)||dueNodes.has(q.primaryNode));if(list.length<5) list=[...new Map([...list,...D.questions].map(q=>[q.id,q])).values()].slice(0,10);start(list,"daily")};$("#btn-treino").onclick=()=>{const disc=$("#f-disciplina").value,tema=$("#f-tema").value,orig=$("#f-origem").value,qtd=Math.max(1,Math.min(30,Number($("#f-qtd").value)||10));let list=D.questions.filter(q=>{const n=node(q.primaryNode);return(!disc||n?.disciplina===disc)&&(!tema||n?.tema===tema)&&(!orig||q.origin===orig)}).slice(0,qtd);start(list,"free")};await stats()}
init().catch(err=>{console.error(err);document.querySelector(".pa-wrap").insertAdjacentHTML("beforeend",'<div class="pa-empty">Não foi possível iniciar o banco local de prática. Recarregue a página.</div>')});
})();