window.PA_DATA = {
  version: "1.1",
  nodes: [
    {id:"PEN-LEG-LEGALIDADE",disciplina:"Direito Penal",tema:"Princípio da legalidade",titulo:"Legalidade penal"},
    {id:"PEN-LEI-TEMPO",disciplina:"Direito Penal",tema:"Lei penal no tempo",titulo:"Lei penal no tempo"},
    {id:"DH-ANPP",disciplina:"Processo Penal",tema:"ANPP",titulo:"Acordo de Não Persecução Penal"},
    {id:"CONST-ART5",disciplina:"Direito Constitucional",tema:"Direitos fundamentais",titulo:"Art. 5º e limitação do poder"},
    {id:"PROC-CONTRADITORIO",disciplina:"Teoria do Processo",tema:"Garantias processuais",titulo:"Contraditório"},
    {id:"PEN-EXEC-REMICAO",disciplina:"Execução Penal",tema:"Remição e remissão",titulo:"Remição e remissão"},
    {id:"DH-HIST-METODO",disciplina:"Direitos Humanos",tema:"Formação histórica",titulo:"Formação histórica dos direitos humanos"},
    {id:"DH-JUSNATURALISMO",disciplina:"Direitos Humanos",tema:"Jusnaturalismo",titulo:"Jusnaturalismo e limitação do poder"},
    {id:"DH-MAGNA-CARTA",disciplina:"Direitos Humanos",tema:"Magna Carta",titulo:"Magna Carta de 1215"}
  ],
  contents: [
    {id:"TXT-VOCAB",titulo:"Vocabulário Jurídico e Latim",url:"/vocabulario/",status:"published",nodes:["PEN-LEG-LEGALIDADE","PEN-LEI-TEMPO","PROC-CONTRADITORIO","PEN-EXEC-REMICAO"]},
    {id:"TXT-DH-ANPP",titulo:"ANPP — Acordo de Não Persecução Penal",url:"/direitos-humanos/anpp-acordo-nao-persecucao-penal.html",status:"published",nodes:["DH-ANPP"]},
    {id:"TXT-DH-ART5",titulo:"O artigo 5º da Constituição Federal",url:"/direitos-humanos/artigo-5-constituicao-federal.html",status:"published",nodes:["CONST-ART5"]},
    {id:"TXT-DH-REMICAO",titulo:"Remição, remissão e perdão estatal",url:"/direitos-humanos/remicao-e-remissao-de-pena.html",status:"published",nodes:["PEN-EXEC-REMICAO"]},
    {id:"TXT-DH-HIST",titulo:"A história do conceito de direitos humanos",url:"/direitos-humanos/historia-conceito-direitos-humanos.html",status:"published",nodes:["DH-HIST-METODO","DH-JUSNATURALISMO","DH-MAGNA-CARTA"]}
  ],
  questions: [
    {id:"Q-LEG-001",type:"multiple_choice",origin:"autoral",primaryNode:"PEN-LEG-LEGALIDADE",difficulty:1,prompt:"Qual fórmula sintetiza classicamente o princípio da legalidade penal?",options:["In dubio pro reo","Nullum crimen, nulla poena sine lege","Iura novit curia","Pacta sunt servanda"],answer:1,explanation:"A fórmula nullum crimen, nulla poena sine lege sintetiza a exigência de lei para definir crimes e penas.",contentId:"TXT-VOCAB"},
    {id:"Q-LEG-002",type:"multiple_choice",origin:"autoral",primaryNode:"PEN-LEG-LEGALIDADE",difficulty:2,prompt:"No vocabulário jurídico estudado, lex stricta está ligada principalmente a qual consequência do princípio da legalidade?",options:["Permitir costume incriminador","Impedir analogia para criar ou agravar incriminação","Autorizar retroatividade gravosa","Dispensar lei escrita"],answer:1,explanation:"Lex stricta impede o emprego de analogia para criar crimes, ampliar incriminações ou agravar a situação do acusado.",contentId:"TXT-VOCAB"},
    {id:"Q-LEG-003",type:"true_false",origin:"autoral",primaryNode:"PEN-LEG-LEGALIDADE",difficulty:2,prompt:"A analogia favorável ao réu é alcançada pela mesma proibição da analogia in malam partem.",options:["Verdadeiro","Falso"],answer:1,explanation:"O material estudado distingue a analogia prejudicial ao acusado, vedada, da analogia favorável.",contentId:"TXT-VOCAB"},
    {id:"Q-LEG-004",type:"short_answer",origin:"autoral",primaryNode:"PEN-LEG-LEGALIDADE",difficulty:2,prompt:"Em uma ou duas frases, explique o sentido de lex praevia.",modelAnswer:"A lei que define o crime e estabelece a pena deve existir antes da prática do fato; trata-se do corolário temporal da legalidade penal.",explanation:"O núcleo é a anterioridade da lei penal e a vedação da retroatividade gravosa.",contentId:"TXT-VOCAB"},

    {id:"Q-TEMPO-001",type:"multiple_choice",origin:"autoral",primaryNode:"PEN-LEI-TEMPO",difficulty:1,prompt:"Lex mitior designa:",options:["Lei posterior mais gravosa","Lei posterior mais favorável","Lei penal temporária","Lei processual penal"],answer:1,explanation:"Lex mitior é a lei penal mais favorável ao agente.",contentId:"TXT-VOCAB"},
    {id:"Q-TEMPO-002",type:"multiple_choice",origin:"autoral",primaryNode:"PEN-LEI-TEMPO",difficulty:1,prompt:"Lex gravior designa:",options:["Lei mais favorável","Lei mais grave ou severa","Lei revogada","Lei excepcional sem vigência"],answer:1,explanation:"Lex gravior é a lei posterior mais gravosa e não retroage para prejudicar fatos anteriores.",contentId:"TXT-VOCAB"},
    {id:"Q-TEMPO-003",type:"multiple_choice",origin:"autoral",primaryNode:"PEN-LEI-TEMPO",difficulty:2,prompt:"A novatio legis in mellius ocorre quando:",options:["A conduta deixa de ser crime","A lei posterior melhora a situação do agente, mas o fato continua criminoso","A lei posterior agrava a pena","Duas leis são combinadas pelo julgador"],answer:1,explanation:"A novatio legis in mellius é uma lei nova mais favorável sem descriminalização do fato.",contentId:"TXT-VOCAB"},
    {id:"Q-TEMPO-004",type:"multiple_choice",origin:"autoral",primaryNode:"PEN-LEI-TEMPO",difficulty:3,prompt:"No material publicado, lex tertia refere-se a:",options:["Lei penal intermediária","Construção de uma terceira disciplina mediante combinação de partes favoráveis de leis sucessivas","Lei criada por medida provisória","Lei temporária aplicada após sua vigência"],answer:1,explanation:"Lex tertia é a construção, pelo julgador, de um regime híbrido mediante combinação de partes de leis sucessivas.",contentId:"TXT-VOCAB"},
    {id:"Q-TEMPO-005",type:"short_answer",origin:"autoral",primaryNode:"PEN-LEI-TEMPO",difficulty:2,prompt:"Diferencie, de forma breve, lex mitior e lex gravior.",modelAnswer:"Lex mitior é a lei penal mais favorável ao agente e pode retroagir em seu benefício; lex gravior é a lei mais severa e não retroage para prejudicá-lo.",explanation:"A distinção central é favorabilidade versus maior gravidade e seus efeitos temporais.",contentId:"TXT-VOCAB"},

    {id:"Q-ANPP-001",type:"multiple_choice",origin:"autoral",primaryNode:"DH-ANPP",difficulty:2,prompt:"Como o texto publicado caracteriza juridicamente o ANPP?",options:["Sentença penal antecipada","Negócio jurídico processual penal com conteúdo penal relevante","Ato administrativo unilateral do juiz","Contrato privado entre investigado e vítima"],answer:1,explanation:"O texto trata o ANPP como negócio jurídico processual penal, submetido à legalidade, voluntariedade, proporcionalidade e controle judicial.",contentId:"TXT-DH-ANPP"},
    {id:"Q-ANPP-002",type:"true_false",origin:"autoral",primaryNode:"DH-ANPP",difficulty:2,prompt:"Se não houver justa causa para a persecução penal, o ANPP é o mecanismo adequado para suprir a fragilidade da investigação.",options:["Verdadeiro","Falso"],answer:1,explanation:"O texto é expresso: sem justa causa, o caminho é o arquivamento ou o aprofundamento investigativo, não o acordo.",contentId:"TXT-DH-ANPP"},
    {id:"Q-ANPP-003",type:"multiple_choice",origin:"autoral",primaryNode:"DH-ANPP",difficulty:2,prompt:"Qual alternativa reúne elementos apresentados no texto como requisitos centrais do ANPP?",options:["Violência grave e pena máxima inferior a quatro anos","Ausência de violência ou grave ameaça, pena mínima inferior a quatro anos e confissão formal e circunstanciada","Somente primariedade e reparação integral","Apenas concordância judicial"],answer:1,explanation:"O estudo destaca ausência de violência ou grave ameaça, pena mínima inferior a quatro anos, confissão formal e circunstanciada e outros requisitos legais.",contentId:"TXT-DH-ANPP"},
    {id:"Q-ANPP-004",type:"multiple_choice",origin:"autoral",primaryNode:"DH-ANPP",difficulty:2,prompt:"Qual é a função do juiz na homologação do ANPP segundo o texto?",options:["Negociar as condições diretamente","Substituir o Ministério Público na avaliação político-criminal","Controlar legalidade, regularidade e voluntariedade","Redigir a proposta inicial"],answer:2,explanation:"O magistrado não atua como negociador; exerce controle jurídico da homologação.",contentId:"TXT-DH-ANPP"},
    {id:"Q-ANPP-005",type:"true_false",origin:"autoral",primaryNode:"DH-ANPP",difficulty:2,prompt:"O texto trata o ANPP como direito subjetivo automático sempre que requisitos objetivos estiverem presentes.",options:["Verdadeiro","Falso"],answer:1,explanation:"O estudo rejeita essa simplificação e destaca a necessidade de avaliação motivada do Ministério Público.",contentId:"TXT-DH-ANPP"},
    {id:"Q-ANPP-006",type:"short_answer",origin:"autoral",primaryNode:"DH-ANPP",difficulty:3,prompt:"Por que o texto afirma que o ANPP pressupõe um caso apto à denúncia?",modelAnswer:"Porque o acordo pressupõe justa causa e elementos suficientes de autoria e materialidade. Se o caso não estiver maduro para a persecução penal, a solução não é negociar responsabilização, mas arquivar ou aprofundar a investigação.",explanation:"A ideia central é que o ANPP não corrige investigação insuficiente.",contentId:"TXT-DH-ANPP"},

    {id:"Q-ART5-001",type:"multiple_choice",origin:"autoral",primaryNode:"CONST-ART5",difficulty:1,prompt:"No texto publicado, a Constituição de 1988 é apresentada, em relação ao período autoritário, principalmente como:",options:["Criação absoluta do Estado brasileiro","Refundação democrática da ordem constitucional brasileira","Continuidade institucional sem ruptura normativa","Documento apenas programático"],answer:1,explanation:"O texto fala em refundação democrática: o Brasil já existia como Estado, mas a ordem constitucional foi reorganizada após o período autoritário.",contentId:"TXT-DH-ART5"},
    {id:"Q-ART5-002",type:"multiple_choice",origin:"autoral",primaryNode:"CONST-ART5",difficulty:2,prompt:"Qual é a tese central do texto sobre o art. 5º?",options:["É apenas uma lista histórica de direitos","Funciona como trincheira normativa da dignidade humana contra o abuso do poder","Tem função exclusivamente simbólica","Protege apenas relações entre particulares"],answer:1,explanation:"A expressão é a própria tese central anunciada no texto.",contentId:"TXT-DH-ART5"},
    {id:"Q-ART5-003",type:"true_false",origin:"autoral",primaryNode:"CONST-ART5",difficulty:2,prompt:"O texto afirma que o art. 5º deve ser lido apenas como memória do passado autoritário, sem função prospectiva.",options:["Verdadeiro","Falso"],answer:1,explanation:"O texto também o apresenta como projeto jurídico voltado a impedir novas formas de abuso do poder.",contentId:"TXT-DH-ART5"},
    {id:"Q-ART5-004",type:"short_answer",origin:"autoral",primaryNode:"CONST-ART5",difficulty:2,prompt:"Em poucas linhas, explique o sentido de 'refundação democrática' usado no texto sobre a Constituição de 1988.",modelAnswer:"Não significa que o Brasil tenha surgido em 1988, mas que, após o período autoritário, a ordem constitucional foi reorganizada em bases democráticas, com limitação jurídica do poder e centralidade dos direitos fundamentais.",explanation:"O ponto-chave é distinguir nascimento do Estado de reorganização democrática da ordem constitucional.",contentId:"TXT-DH-ART5"},

    {id:"Q-PROC-001",type:"multiple_choice",origin:"autoral",primaryNode:"PROC-CONTRADITORIO",difficulty:1,prompt:"O contraditório se resume à mera ciência dos atos processuais?",options:["Sim","Não; inclui possibilidade real de manifestação e influência legítima na decisão","Sim, salvo no processo penal","Somente em processos administrativos"],answer:1,explanation:"O verbete publicado enfatiza ciência dos atos e possibilidade efetiva de manifestação e influência.",contentId:"TXT-VOCAB"},
    {id:"Q-PROC-002",type:"short_answer",origin:"autoral",primaryNode:"PROC-CONTRADITORIO",difficulty:2,prompt:"Explique por que 'ser informado' não esgota o contraditório.",modelAnswer:"Porque o contraditório exige não apenas ciência dos atos, mas oportunidade real de manifestação e participação capaz de influenciar legitimamente a decisão.",explanation:"A dimensão participativa é essencial ao conceito trabalhado no site.",contentId:"TXT-VOCAB"},

    {id:"Q-REM-001",type:"multiple_choice",origin:"autoral",primaryNode:"PEN-EXEC-REMICAO",difficulty:1,prompt:"Na execução penal de adultos, qual termo técnico designa o abatimento de parte da pena por trabalho, estudo ou hipóteses admitidas?",options:["Remissão","Remição","Anistia","Graça"],answer:1,explanation:"O texto distingue remição, com ç, de remissão, com ss.",contentId:"TXT-DH-REMICAO"},
    {id:"Q-REM-002",type:"multiple_choice",origin:"autoral",primaryNode:"PEN-EXEC-REMICAO",difficulty:2,prompt:"Segundo o texto publicado, qual é a proporção legal indicada para remição pelo trabalho?",options:["1 dia de pena a cada 2 dias de trabalho","1 dia de pena a cada 3 dias de trabalho","1 dia de pena a cada 5 dias de trabalho","2 dias de pena a cada 3 dias de trabalho"],answer:1,explanation:"O texto registra a regra de um dia de pena remido a cada três dias de trabalho.",contentId:"TXT-DH-REMICAO"},
    {id:"Q-REM-003",type:"multiple_choice",origin:"autoral",primaryNode:"PEN-EXEC-REMICAO",difficulty:2,prompt:"Qual proporção de estudo é indicada no texto para remir um dia de pena?",options:["6 horas em um único dia","12 horas de frequência escolar divididas em pelo menos 3 dias","10 horas em pelo menos 2 dias","20 horas em qualquer período"],answer:1,explanation:"O texto registra doze horas de frequência escolar, divididas em pelo menos três dias, para remição de um dia.",contentId:"TXT-DH-REMICAO"},
    {id:"Q-REM-004",type:"true_false",origin:"autoral",primaryNode:"PEN-EXEC-REMICAO",difficulty:2,prompt:"No ECA, remissão e remição de pena são o mesmo instituto.",options:["Verdadeiro","Falso"],answer:1,explanation:"A remissão no sistema socioeducativo é instituto próprio e não corresponde à remição da execução penal adulta.",contentId:"TXT-DH-REMICAO"},
    {id:"Q-REM-005",type:"short_answer",origin:"autoral",primaryNode:"PEN-EXEC-REMICAO",difficulty:2,prompt:"Diferencie remição e remissão em uma resposta curta.",modelAnswer:"Remição, com ç, é o abatimento de parte da pena na execução penal, especialmente por trabalho ou estudo. Remissão, com ss, possui outros sentidos jurídicos e, no ECA, pode funcionar como forma de exclusão, suspensão ou extinção do procedimento socioeducativo.",explanation:"A grafia muda o instituto jurídico.",contentId:"TXT-DH-REMICAO"},

    {id:"Q-DHHIST-001",type:"true_false",origin:"autoral",primaryNode:"DH-HIST-METODO",difficulty:1,prompt:"O texto sobre a história dos direitos humanos apresenta esse processo como uma linha reta e contínua de progresso moral.",options:["Verdadeiro","Falso"],answer:1,explanation:"O texto rejeita explicitamente uma leitura linear e destaca conflitos, crises, guerras, transformações e lutas sociais.",contentId:"TXT-DH-HIST"},
    {id:"Q-DHHIST-002",type:"multiple_choice",origin:"autoral",primaryNode:"DH-HIST-METODO",difficulty:2,prompt:"Qual cuidado metodológico o texto considera necessário ao estudar a história dos direitos humanos?",options:["Projetar o conceito atual sobre todas as épocas","Tratar todo documento antigo como declaração universal","Distinguir o conceito contemporâneo de seus antecedentes, matrizes e etapas de formação","Ignorar ideias anteriores ao século XX"],answer:2,explanation:"O texto recomenda evitar anacronismo e reconhecer antecedentes sem equipará-los ao sistema contemporâneo.",contentId:"TXT-DH-HIST"},
    {id:"Q-DHHIST-003",type:"short_answer",origin:"autoral",primaryNode:"DH-HIST-METODO",difficulty:2,prompt:"Por que seria anacrônico afirmar que a Antiguidade já possuía direitos humanos no mesmo sentido contemporâneo?",modelAnswer:"Porque existiam ideias de justiça, lei natural, dignidade e limitação do poder, mas ainda não um sistema internacional de direitos reconhecidos universalmente à pessoa humana nos moldes contemporâneos.",explanation:"O exercício pede distinguir antecedentes filosóficos da formulação jurídica moderna.",contentId:"TXT-DH-HIST"},

    {id:"Q-JUS-001",type:"multiple_choice",origin:"autoral",primaryNode:"DH-JUSNATURALISMO",difficulty:1,prompt:"Qual é o núcleo comum do jusnaturalismo apresentado no texto?",options:["A lei estatal é sempre justa","Existe uma ordem de justiça anterior ou superior ao direito positivo","Somente costumes criam direito","Direito e moral são conceitos necessariamente idênticos"],answer:1,explanation:"O texto apresenta o jusnaturalismo como tradição que reconhece uma ordem normativa superior à simples vontade do legislador.",contentId:"TXT-DH-HIST"},
    {id:"Q-JUS-002",type:"multiple_choice",origin:"autoral",primaryNode:"DH-JUSNATURALISMO",difficulty:2,prompt:"Por que o jusnaturalismo é relevante como matriz remota dos direitos humanos segundo o texto?",options:["Porque elimina a necessidade de constituições","Porque afirma limites superiores ao poder e fornece base para a ideia de direitos inerentes à pessoa","Porque transforma automaticamente toda moral em lei positiva","Porque substitui o direito internacional"],answer:1,explanation:"Sua importância está na ideia de que o poder não é absoluto e pode ser julgado por critérios superiores de justiça.",contentId:"TXT-DH-HIST"},

    {id:"Q-MAGNA-001",type:"true_false",origin:"autoral",primaryNode:"DH-MAGNA-CARTA",difficulty:1,prompt:"A Magna Carta de 1215 nasceu como uma declaração democrática e universal de direitos humanos.",options:["Verdadeiro","Falso"],answer:1,explanation:"O texto destaca que ela foi um acordo imposto ao rei por setores da nobreza em contexto político específico, não uma declaração universal moderna.",contentId:"TXT-DH-HIST"},
    {id:"Q-MAGNA-002",type:"multiple_choice",origin:"autoral",primaryNode:"DH-MAGNA-CARTA",difficulty:2,prompt:"Qual é a relevância histórica atribuída à Magna Carta no texto?",options:["Criação do sufrágio universal","Marco simbólico de limitação jurídica do poder real","Criação da ONU","Primeira constituição escrita brasileira"],answer:1,explanation:"O documento é tratado como marco simbólico na contenção jurídica de abusos do poder monárquico.",contentId:"TXT-DH-HIST"}
  ]
};
